### ISSUE TITLE
[Javadoc] The search bar takes the user to an incorrect url, resulting in 404 error

### ISSUE THREAD

**Issue by AnthonyWeston** [tdf/odftoolkit#152] opened 2022-01-20 20:30 UTC
Steps to replicate:

1. Open https://odftoolkit.org/api/odfdom in the browser
2. Search for OdfElement in the Search bar
3. Click the search result for OdfElement
_Expected result:_ The user is taken to the Javadoc page for the selected item
_Actual result:_ The user is taken to https://odftoolkit.org/api/odfdom/undefined/org/odftoolkit/odfdom/pkg/OdfElement.html, and sees 404 Not Found on the page.

The user is able to navigate to the page by removing the `undefined/` from the url.

**Comment by svanteschubert** [comment] 2022-01-20 20:44
Thanks for the pointer, others got this working with the help of the following option in the java doc maven plugin configuration

`<additionalJOption>--no-module-directories</additionalJOption>`

https://stackoverflow.com/a/52603413/7919834

**Comment by AnthonyWeston** [comment] 2022-01-21 00:50
Thanks for the quick response, but I was referring to the live website at https://odftoolkit.org/api/odfdom rather than a local build.

**Comment by svanteschubert** [comment] 2022-01-21 08:07
Yes, indeed, I have not fixed it, yet. Just pointed out the problem. But will do the patch today and ask Michael to review and upload the JavaDoc to the site. Thanks again. :-)

**Comment by svanteschubert** [comment] 2022-01-21 14:34
I found out that the problem is just a JDK 11 bug currently: https://bugs.openjdk.java.net/browse/JDK-8244171
referenced from https://bugs.openjdk.java.net/browse/JDK-8215291

Indeed, when building with LTS JDK 17 (Linux) the JavaDoc issue does no longer occur. 
I will fix it for the latest version: https://tdf.github.io/odftoolkit/javadoc.html

@mistmist Could you please rebuild the 0.9.0 and 0.10.0 release java doc and copy it to odftoolkit.org?

**Comment by mistmist** [comment] 2022-01-21 19:04
fixed by commit c844b27dd9c08be2963acfe22c2d4af258225d24 and copied to odftoolkit.org

**Closed by mistmist** 2022-01-21 19:04 UTC
