### ISSUE TITLE
Error in line deletion in table from odf text document

### ISSUE THREAD

**Issue by Boarschti42** [tdf/odftoolkit#298] opened 2024-06-02 14:32 UTC
Hi, 

we have an issue while deleting some lines in an odt document containing tables. The issue: if the table has merged cells (see attachment sample), the deletion of lines containing this merged cells is not possible. If the merged cells are removed, everything works fine. 

Error is located here: 
```
java.lang.NullPointerException: Cannot invoke "org.odftoolkit.odfdom.doc.table.OdfTableCell.isCoveredElement()" because "cell" is null
	at org.odftoolkit.odfdom.doc.table.OdfTableRow.removeAllCellsRelationship(OdfTableRow.java:868)
	at org.odftoolkit.odfdom.doc.table.OdfTable.removeRowsByIndex(OdfTable.java:1816)
	at de.rekn.odftest.DeleteLineTest.testDeleteLine(DeleteLineTest.java:20)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Sample code for reproducing this error:
``` java

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.odftoolkit.odfdom.doc.OdfTextDocument;
import org.odftoolkit.odfdom.doc.table.OdfTable;

public class DeleteLineTest {

    @Test
    public void testDeleteLineText() throws URISyntaxException, Exception {
        URL resURL = this.getClass().getResource("/odfWriterTest.odt");

        OdfTextDocument document = OdfTextDocument.loadDocument(Path.of(resURL.toURI()).toFile());
        OdfTable pTable = document.getTableList(true).get(0);

        assertDoesNotThrow(() -> pTable.removeRowsByIndex(2, 1));
    }

}


```
[Testfile odfWriterTest.odt](https://github.com/user-attachments/files/15525658/odfWriterTest.odt)

Can you confirm this is a bug? Are there other ways to solve this problem?

Thanks in advance

Boarschti

**Comment by Boarschti42** [comment] 2024-06-08 09:25
Hi, 
Are there any posibilities to go around that issue? I would commit a PR, but i dont know how this function is intended to be used and working. 
Any help would be nice :)

Thank you

**Comment by svanteschubert** [comment] 2024-06-08 12:27
@Boarschti42 
Let me try to explain, the document you sent has a table with three rows and three columns.
The first cell is overlapping over three rows, I made the cells red:
![image](https://github.com/tdf/odftoolkit/assets/825051/8de8b65e-e09c-4b76-a954-2e8aa66200f2)
These cells are being "covered" and marked as those in the XML (as well as red) ->
![image](https://github.com/tdf/odftoolkit/assets/825051/9b0fd7a2-683e-4cd7-85ee-68f3e3e16327)

Would you be so kind as to extend an existing test (or overtake otherwise your test) with your test document for the master branch? 
I am sorry, I am a bit under time pressure these days...
Thanks in advance,
Svante

PS: Thank you for the reminder, I should never let anyone wait longer than 3 days - unless I am on vacation but then Michael would answer :-)

**Comment by svanteschubert** [comment] 2024-06-08 12:41
@Boarschti42 Of course, a PR is most welcome. I assume during the deletion of the row a cell is not returned for some reason in the loop of 
https://github.com/tdf/odftoolkit/blob/master/odfdom/src/main/java/org/odftoolkit/odfdom/doc/table/OdfTableRow.java#L259C24-L259C49
A debug in your environment should reveal the problem. Thanks again in advance for your help! :-)

**Comment by Boarschti42** [comment] 2024-07-03 16:04
Hi, are there any things that can help fix this? yo know something about this issue?

thank :)

**Comment by svanteschubert** [comment] 2024-07-03 23:02
Sorry, had some dead lines, but I will start a branch based on your test and test case to see if I can reproduce the problem. 
If the exception occurs, perhaps I can spot easily the problem or we can start work on that branch.

@Boarschti42 Thanks for your patience!

**Comment by svanteschubert** [comment] 2024-07-07 12:58
I added your test document to a branch and added your JUnit5 test as a JUnit4 test (I happily take patches from JUnit4 to JUnit5, but please announce it first on the dev mailing list, so we won't oversee arguments against it and first ask for those).

As you stated the NullPointerException could be reproduced.
I then deleted the middle row with LibreOffice Writer and saved it to check how the XML might look.

1. The middle row `<table:table:row>` of course had been deleted
2. The first cell in the first row has one less cell to span (overlap), therefore the attribute `@table:number-rows-spanned="3"` changed its value to `"2"`

In the end, the problem was a deletion of the covered table cell in the second row, which led to a miscounting of cells in this row in this loop and to the NullPointerException. No idea, why this had been once added - my bet is on the IBM Beijing team - but mistakes are being made. All tests - including yours - run green afterwards.

Nevertheless, there is still some problem in the mapping to my beloved ODF API as JSON, I will file a follow-up issue.

**Closed** 2024-07-08 14:12 UTC
Labels: bug, review wanted

**Comment by Boarschti42** [comment] 2024-07-08 16:36
Thank you so much for this fix. Is there a timeline for 0.13.0 or a snapshot?

**Comment by svanteschubert** [comment] 2024-07-08 17:33
Good idea! Will do a SNAPSHOT this week, currently on the road
